import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "lenis/dist/lenis.css";
import "@/css/glass.css";
import LenisProvider from "@/app/components/lenis-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello, Niranjan here...",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={` ${inter.variable} antialiased  relative`}>
        <LenisProvider>
          <Header />

          <main>{children}</main>

          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
